GET http://localhost:5000/

###
GET http://localhost:5000/api/students

###
POST http://localhost:5000/api/students
Content-Type: application/json

{
    "nama_siswa": "septi",
    "alamat_siswa": "bojongsoang",
    "tanggal_siswa": "2025-09-11",
    "jurusan_siswa": "otomotif"
}

###
POST http://localhost:5000/api/students
Content-Type: application/json

{
  "nama_siswa": "damay",
  "alamat_siswa": "ciganitri",
  "tanggal_siswa": "2025-08-11",
  "jurusan_siswa": "tekmek"
}

